### ISSUE TITLE
Add implementations in other languages

### ISSUE THREAD

**Issue by Aliuken** [OculusVR/Flicks#10]
I think implementations in other languages like Rust or Go are needed.

**Comment by orthros** [comment]
Seems like a fairly straightforward implementation in Go (I am unfamiliar with Rust). I might try hacking out a Go library for it tonight.

**Comment by abhinuvpitale** [comment]
I think an implementation in Python would be simple, I ll give it a shot using the time library!

**Comment by orent** [comment]
https://docs.python.org/3.5/library/fractions.html

**Comment by sukhoi** [comment]
I can try implementing with Java and also check if the code is compatible with C.

**Comment by blackencino** [comment]
I'll review any pull requests which are written in a similar coding style and are well documented and tested, in Python, Go, or Rust. Until then, I'll close this issue.
