### ISSUE TITLE
1/24 fps = 1 frame per 24 seconds

### ISSUE THREAD

**Issue by recodyx** [OculusVR/Flicks#15]
The documentation is a bit confusing.
1/24 fps is 1/24 f/s isn't it?

I believe it should be:
24 fps = 29400000 flicks

Sorry if I'm wrong.

**Comment by BenjaminHae** [comment]
24 fps means 24 frames per second so one frame in this case takes 29400000 flicks is a more precise phrasing. I think it's okay in the documentation.

> I believe it should be:
> 24 fps = 29400000 flicks

On the left hand side you have
`24 fps = 24 frames/second`
On the right hand side it's
`29400000 flicks = 29400000 * 1/705600000 s`
So the units don't match.

**Comment by blackencino** [comment]
24 fps frame is intended to mean, "one frame at 24 frames per second", which I think is reasonably clear as written.
