### ISSUE TITLE
Readme should mention that 144hz is divisible too

### ISSUE THREAD

**Issue by thomcc** [OculusVR/Flicks#16]
This is a reasonably common refresh rate on newer monitors, and it works fine with Flicks (705600000flicks/sec * 1/144 sec/frame = 4900000 flicks), but it's not mentioned in the README.

I had initially thought this was an unfortunate oversight, but it turns out it's just missing from the documentation.

(edit: Looking at the derivation file, it seems like this might have been unintentional, but it seems worth mentioning nonetheless)

**Comment by blackencino** [comment]
This frame rate has not come up in any of the production examples I've seen or had shared. I'll make a note that it is supported, but I won't modify the design criteria to explicitly include this.

**Comment by blackencino** [comment]
A note has been added in the header and README, though design criteria are unchanged.
