### ISSUE TITLE
1/705600000 is not enough

### ISSUE THREAD

**Issue by vipper36** [OculusVR/Flicks#19]
Here is current additional compatible list:
144Hz (monitor) -> 144 fps frame: 4900000 flicks
240Hz (monitor and high-speed camera) -> 240 fps frame: 2940000 flicks
480Hz (high-speed camera) -> 480 fps frame: 1470000 flicks
960Hz (high-speed camera) -> 960 fps frame: 735000 flicks
2.8224MHz (DSD64 audio) -> 2822400 fps frame: 250 flicks
5.6448MHz (DSD128 audio) -> 5644800 fps frame: 125 flicks

Here is current incompatible list:
384kHz (high-end PCM audio) -> 384000 fps frame: 1837.5 flicks
768kHz (high-end PCM audio) -> 768000 fps frame: 918.75 flicks
11.2MHz (DSD256 audio) -> 11289600 fps frame: 62.5 flicks
22.5792MHz (DSD512 audio) -> 22579200 fps frame: 31.25 flicks

I suggest to make the flick value down to 1/(705600000*4) = 1/2822400000.

**Comment by mdrost** [comment]
I think they want to keep flick larger than nanosecond so valuing it down is not an option.

**Comment by vipper36** [comment]
I'm not sure why they need to keep the flick larger than nanosecond.
IIRC TSC/HPET clocksource uses sub-nanosecond resolution at least on Linux.
http://elixir.free-electrons.com/linux/v4.15-rc9/source/arch/x86/kernel/hpet.c#L946
Though there are no user API to get sub-nanosecond time, we must be able to get the sub-nanosecond time from [vvar] memory region of vdso.
http://elixir.free-electrons.com/linux/latest/source/arch/x86/entry/vdso/vclock_gettime.c#L207
https://gist.github.com/vipper36/2c9603191675cdf6268a0938fa4bc331

**Comment by blackencino** [comment]
Hey folks,

Thank you for the input. A design criteria was to be greater than or equal to a nanosecond, and the high-resolution audio formats you shared were not considered an important consideration for our primary use cases. I'll update the readme to indicate that these formats aren't supported.

With this unit, we were definitely aiming for the 95% or 99% most common use cases in the media types that we encounter and would be working with. The high-end audio formats you mention are outside that for us, for now.

Chris

(though deciflicks would work!)

**Comment by sergedundich** [comment]
@vipper36 @blackencino Actually there is no need to make it less than nanosecond to support those rates.

5/(705600000*4) = 1/564480000 would do perfectly.

The only drawback of 564480000 would be that it is not divisible by 25*1000 - but this was arbitrary and pointless criterion anyway. You really **do** need to make it divisible by 24000, 48000, 30000, 60000, 120000 to support NTSC frame rates - thus it is **not** arbitrary demand for those (24000/1001 Hz, 30000/1001 Hz and their multiples are well defined as a frame frequency in NTSC and many compatible standards). But there is no NTSC-type FPS based on PAL (no such thing as 25000/1001 Hz in any standard) - so making it divisible by 25000 is arbitrary and serves no purpose.
