### ISSUE TITLE
Readme: maximum frequency of human hearing is incorrect

### ISSUE THREAD

**Issue by reklawnos** [OculusVR/Flicks#2]
Sorry that this is really pedantic, but the upper end of the range of frequencies humans can hear is typically cited as being 20kHz, not 48kHz. See [Wikipedia](https://en.wikipedia.org/wiki/Hearing_range), for example. Also, going strictly by that value, 44.1kHz should be considered the lowest sample rate that can accurately reproduce all audible frequencies (given that its Nyquist frequency is 22.05kHz). There's some more info about that [here](https://en.wikipedia.org/wiki/44,100_Hz#Human_hearing_and_signal_processing).

One example of a replacement for that sentence would be:

> While the 44.1kHz sample rate can be used to reproduce all frequencies in the typical human hearing range, the higher sample rates are used for working with audio files which might later be resampled or retimed.

**Comment by blackencino** [comment]
Thanks for this correction, I'll make sure that this statement is corrected.

**Comment by chaboud** [comment]
It could be corrected to say "minimum sample rate that can reproduce the typical human hearing range", as there's Nyquist to consider.  However, studies in phase discrimination have shown spatial precision greater than audible frequency range, making the whole statement more likely to cause arguments than anything else.  I'd just pull it and stick with "common audio industry sample rates" or something like that.

48KHz is typically used for being above 44.1KHz but also being pleasantly divisible by video frame rates, something I'm betting blackencino already knows very well.

**Comment by meshula** [comment]
I'd agree with the previous posters that it'd be best to stick to wording mentioning standard sampling rates, rather than opening a can of worms on human perception :) I can't strictly resist that can of worms, and posit that @chaboud might be referring to this research, or one of the studies it references, all of which I am quite fond of. https://web.wpi.edu/Pubs/E-project/Available/E-project-121311-121322/unrestricted/Samir_Zutshi_IQP.pdf

**Comment by blackencino** [comment]
I'll fix it!

**Comment by blackencino** [comment]
Fixed!
