### ISSUE TITLE
It's actually great for NTSC rates

### ISSUE THREAD

**Issue by Dithermaster** [OculusVR/Flicks#3]
You said "The NTSC variations (~29.97, etc) are actually defined as 24 * 1000/1001 and 30 * 1000/1001, which are impossible to represent exactly in a way where 1 second is exact, so we don't bother - they'll be inexact in any circumstance."

But in reality, your time unit works perfectly for them too! 29.97 (30000/1001) is 23543520 flicks. 23.976 (24000/1001) is 29429400 flicks. 59.94 (60000/1001) is 11771760 flicks.

Also, the "incorrect" values (29.97, 23.976, 59.94 "exact") are all fractional values of flicks, which is great. People shouldn't be using them anyway!

You've done a great service to those who have to deal with NTSC rates!

**Comment by kepstin** [comment]
Just in case anyone doubts the math,
```
 1001   11760    11771760
 ---- × ----- = ---------
60000   11760   705600000

 1001   23520    23543520
 ---- × ----- = ---------
30000   23520   705600000

 1001   29400    29429400
 ---- × ----- = ---------
24000   29400   705600000
```
This really all falls out naturally from the decision to ensure that 1000× versions of all the common rates were supported; it means the flicks denominator is divisible by 60000, 30000, and 24000.

**Comment by blurbusters** [comment]
And I really appreciate this is future-proof with future refresh rates, including:

- 240 Hz
- 480 Hz
- 960 Hz
- 1000 Hz
- 1920 Hz
- 2000 Hz

There was recently the first [consumer test of 480Hz](http://www.blurbusters.com/480hz).  There's also a good article about future 1000 Hz displays which shows promise of blurless sample-and-hold (strobeless low-persistence) -- [Blur Busters Law: The Amazing Journey To Future 1000Hz Displays](https://www.blurbusters.com/blur-busters-law-amazing-journey-to-future-1000hz-displays-with-blurfree-sample-and-hold/).

**Comment by chaboud** [comment]
705600000 is the LCM of {24000, 25000, 30000, 48000, 50000, 60000, 90000, 100000, 120000, 8000, 16000, 22050, 24000, 32000, 44100, 48000, 88200, 96000, 192000}, so that makes sense.

On that note, derivation could be done using Euclid's method (LCM via GCD via residual modulo).

**Comment by gonewest818** [comment]
Right.  Expressed in Clojure, the derivation is very compact:
```

(def terms '(24000
             25000
             30000
             48000
             50000
             60000
             90000
             100000
             120000
             8000
             16000
             22050
             24000
             32000
             44100
             48000
             88200
             96000
             192000))

(defn gcd [a b]
  (if (zero? b)
    a
    (recur b (mod a b))))

(defn lcm [a b]
  (/ (* a b) (gcd a b)))

(reduce lcm terms)
;; => 705600000
```

**Comment by kepstin** [comment]
It's getting a bit off-topic in here - this issue is about NTSC framerates (those with the 1000/1001 multiplier). Someone has already made a pull request for calculating the flicks value directly (via gcd) over in #5

**Comment by emattheis** [comment]
Just because you can represent an NTSC frame duration in flicks doesn't make it useful for the stated motivation of this project. It's still impossible to accumulate an integral number of NTSC frames and arrive at exactly one second.

**Comment by Dithermaster** [comment]
@emattheis : What's so special about one second? Just the ability to represent these frame periods exactly using integers is a great thing in and of itself. Other attempted solutions, such as WMF 100-nanosecond units, cause tricky bugs with NTSC rates: one frame period is 333,666 and 2/3 of those - the fractional part is lost - and if you accumulate these, you get in trouble. I know, I've had to deal with these kinds of bugs in real applications that use that timebase.

**Comment by blackencino** [comment]
Excellent! I've updated all the documents to reflect this, and have
explicitly included tests for this in the design verificaiton code.

**Comment by emattheis** [comment]
@Dithermaster not sure - I’m just saying that’s the stated motivation for this project. I’m curious to see how folks would use this flicks concept. Those of us working with NTSC video rates are already forced to do so within the bounds of other APIs and timing schemes. I don’t get how flicks helps. Would love to see an example.

**Comment by kepstin** [comment]
Looking at Christopher's recent changes regarding the NTSC rates, I notice a few more problems...

> NTSC IS NOT EXPLICITLY SUPPORTED IN ALL OF ITS SUBTLE NUANCES

This is OK. I could see you not wanting to worry about stuff like drop frame SMTPE timecodes.

> The NTSC variations (~23.976, ~29.97, etc) are approximately defined as 24 * 1000/1001 and 30 * 1000/1001, etc.

Missed removing an "approximately" here; the 1000/1001 figures are exact (this goes back to the analogue standards, and is by definition).

> Many folks online have pointed out that NTSC technically has a variable frame rate

This needs a reference. Analogue NTSC is exactly 60*1000/1001 *fields* per second, no more, no less.
In computer video where you have deinterlaced/detelecined video you might have mixed 60/30/24 rates, but this works perfectly fine in Flicks - indeed, having a GCD timebase makes mixing content in any different framerate very easy.

> So we'll stick with the 1000/1001 approximations, and leave it at that!

Again, the 1000/1001 values are not approximate.

**Comment by Dithermaster** [comment]
Exactly. The "approximately" can be removed and the whole bit about "variable frame rate" and "1000/1001 approximations" can be removed. NTSC is not variable, and 1000/1001 is not approximate.

**Comment by Dithermaster** [comment]
> I don’t get how flicks helps. Would love to see an example.

OK, let's say you were writing a video editor, and you wanted to place clips on a timeline. Their starting and ending positions (as well as trim points) are represented using numbers. Floating point is not appropriate for that because it loses precision as the numbers get bigger, and the math gets "fuzzy" and comparisons require epsilons. Yuck. So you use integers. What should the period of each count be? Maybe you choose something like 1e-7 seconds (Microsoft and others did, after all). Now NTSC frame periods get rounded, and you have lots of subtle bugs and hacky code to work around them. You have to make rules like "don't multiply a frame count by a frame period, because the frame period might have been rounded". If you used Flicks instead, timelines and media of any supported framerate (Flicks supports a large inclusive list) are exactly representable. No more weird rounding, and far less hacky code to deal with off-by-a-little values that results from that. You can do things like frame count times frame period and actually get a correct value. The only downside I see is if a new framerate comes along someday that doesn't have a period that's exactly representable in Flicks, then you're hosed.

**Comment by emattheis** [comment]
@Dithermaster Thanks! Flicks makes a lot more sense in that context. I was thinking about it from the perspective of converting frames to ticks of the MPEG clock where there is already an established algorithm using integer math and I don't think flicks will work for representing individual 27kHz or 90MHz ticks.

**Comment by blackencino** [comment]
I'll remove the remaining 'approximately's. The whole NTSC standard is
outside my wheelhouse, and I only noted that it kinda sorta worked as an
afterthought, which was clearly messy.

Thanks for the feedback.
