### ISSUE TITLE
How to abbreviate flick?

### ISSUE THREAD

**Issue by szabolcsdombi** [OculusVR/Flicks#9]

**Comment by raghsgit** [comment]
Fk

**Comment by ronniereeder** [comment]
fK

**Comment by ghost** [comment]
flick

**Comment by marvin-SL** [comment]
Flick.com

**Comment by LunarRed** [comment]
1 flick = 1fk
1,000 flicks = 1Kfk
1,000,000 flicks = 1Mfk
1,000,000,000 flicks = 1Gfk

**Comment by Xerios** [comment]
![](http://savethevowels.org/posts/lmimg/flick.gif)

I'd go with the bad kerning version and count them in fcks, e.g. "how many fcks does your simulation give?"

**Comment by mbjorkegren** [comment]
flk

**Comment by Ybalrid** [comment]
I like "flk", and I like using the metric system prefix like @LunarRed did

**Comment by blackencino** [comment]
I have no explicit preference here... flk seems reasonable.
